# Generated by Django 5.1.5 on 2025-05-21 13:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('accessoires', models.TextField(blank=True)),
                ('acheteur', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('possesseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_empruntes', to='lycee.enseignant')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_responsables', to='lycee.enseignant')),
                ('salle_actuelle', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lycee.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('occasion', models.CharField(max_length=255)),
                ('objectif_utilisation', models.TextField()),
                ('accessoires_etat', models.TextField(blank=True)),
                ('ancien_possesseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anciens_emprunts', to='lycee.enseignant')),
                ('nouveau_possesseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nouveaux_emprunts', to='lycee.enseignant')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lycee.materiel')),
                ('lieu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lycee.salle')),
            ],
        ),
    ]
