# Generated by Django 5.1.5 on 2025-06-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_enseignant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(blank=True, max_length=255)),
                ('present', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='materiel',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_possedes', to='lycee.enseignant'),
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='accessoires',
        ),
        migrations.AlterField(
            model_name='materiel',
            name='salle_actuelle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lycee.salle'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='accessoires',
            field=models.ManyToManyField(blank=True, to='lycee.accessoire'),
        ),
    ]
