# Generated by Django 5.1.5 on 2025-06-09 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0003_accessoire_materiel_proprietaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='accessoires',
        ),
        migrations.AddField(
            model_name='accessoire',
            name='materiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessoires', to='lycee.materiel'),
        ),
    ]
