# Generated by Django 5.1.5 on 2025-06-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0004_remove_materiel_accessoires_accessoire_materiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='occasion',
        ),
    ]
